###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import sqlite3 as sq

# Foreign born Population by Place of Birth for the GNRC Senior Centers

This data is not available on MySidewalk, where these senior center profiles are hosted. This notebook contains the API pulls and the data cleaning process necessary to include this as outside data in these profiles.

In [2]:
conn = sq.connect(r'G:\GNRC_GIS_STRUCTURE\Census\Outputs/CensusBureau.db')
sql_query = pd.read_sql('SELECT * FROM [ACS5_2024_1]', conn)
ACS5_1 = pd.DataFrame(sql_query)
sql_query = pd.read_sql('SELECT * FROM [ACS5_2024_2]', conn)
ACS5_2 = pd.DataFrame(sql_query)
ACS5 = ACS5_1.merge(ACS5_2, on = ['NAME', 'GEO_ID'])
data = ACS5

In [3]:
geos = ['Cheatham County, Tennessee', 'Davidson County, Tennessee', 'Dickson County, Tennessee', 'Houston County, Tennessee', 'Humphreys County, Tennessee', 
        'Maury County, Tennessee', 'Montgomery County, Tennessee', 'Robertson County, Tennessee', 'Rutherford County, Tennessee', 'Stewart County, Tennessee', 
        'Sumner County, Tennessee', 'Trousdale County, Tennessee', 'Williamson County, Tennessee', 'Wilson County, Tennessee']

In [4]:
cols1 = ['NAME', 'Foreign Born Population' ,'ForeignBorn:Europe' ,
        'ForeignBorn:Asia' ,'ForeignBorn:Africa' ,'ForeignBorn:Oceania' ,'ForeignBorn:Americas' ,'ForeignBorn:Central & South America, Caribbean' ,
        'ForeignBorn:Canada & Other Northern American' ,'ForeignBorn:Europe:NorthernEurope' ,

        'ForeignBorn:Europe:NorthernEurope:Denmark' ,'ForeignBorn:Europe:NorthernEurope:Ireland' ,'ForeignBorn:Europe:NorthernEurope:Norway' ,
        'ForeignBorn:Europe:NorthernEurope:Sweden' ,'ForeignBorn:Europe:NorthernEurope:UK' ,'ForeignBorn:Europe:NorthernEurope:UK:Excluding England and Scotland' ,
        'ForeignBorn:Europe:NorthernEurope:UK:England' ,'ForeignBorn:Europe:NorthernEurope:UK:Scotland' ,'ForeignBorn:Europe:NorthernEurope:Other' ,
        'ForeignBorn:Europe:WesternEurope' ,'ForeignBorn:Europe:WesternEurope:Austria' ,'ForeignBorn:Europe:WesternEurope:Belgium' ,
        'ForeignBorn:Europe:WesternEurope:France' ,'ForeignBorn:Europe:WesternEurope:Germany' ,'ForeignBorn:Europe:WesternEurope:Netherlands' ,
        'ForeignBorn:Europe:WesternEurope:Switzerland' ,'ForeignBorn:Europe:WesternEurope:Other' ,'ForeignBorn:Europe:SouthernEurope' ,
        'ForeignBorn:Europe:SouthernEurope:Greece' ,'ForeignBorn:Europe:SouthernEurope:Italy' ,'ForeignBorn:Europe:SouthernEurope:Portugal' ,
        'ForeignBorn:Europe:SouthernEurope:Azores Islands' ,'ForeignBorn:Europe:SouthernEurope:Spain' ,'ForeignBorn:Europe:SouthernEurope:Other' ,
        'ForeignBorn:Europe:EasternEurope' ,'ForeignBorn:Europe:EasternEurope:Albania' ,'ForeignBorn:Europe:EasternEurope:Belarus' ,
        'ForeignBorn:Europe:EasternEurope:Boznia and Herzegovina' ,'ForeignBorn:Europe:EasternEurope:Bulgaria' ,'ForeignBorn:Europe:EasternEurope:Croatia' ,
        'ForeignBorn:Europe:EasternEurope:Czechoslovakia (Czech Republic and Slovakia)' ,'ForeignBorn:Europe:EasternEurope:Hungary' ,
        'ForeignBorn:Europe:EasternEurope:Latvia' ,'ForeignBorn:Europe:EasternEurope:Lithuania' ,'ForeignBorn:Europe:EasternEurope:Moldova' ,
        'ForeignBorn:Europe:EasternEurope:North Macedonia (Macedonia)' ,'ForeignBorn:Europe:EasternEurope:Poland' ,'ForeignBorn:Europe:EasternEurope:Romania' ,
        'ForeignBorn:Europe:EasternEurope:Russia' ,'ForeignBorn:Europe:EasternEurope:Serbia' ,'ForeignBorn:Europe:EasternEurope:Ukraine' ,
        'ForeignBorn:Europe:EasternEurope:Other' , 'ForeignBorn:Asia:EasternAsia' ,'ForeignBorn:Asia:EasternAsia:China' ,
        'ForeignBorn:Asia:EasternAsia:China Excluding Hong Kong and Taiwan' ,'ForeignBorn:Asia:EasternAsia:Hong Kong' ,'ForeignBorn:Asia:EasternAsia:Taiwan' ,
        'ForeignBorn:Asia:EasternAsia:Japan' ,'ForeignBorn:Asia:EasternAsia:Korea' ,'ForeignBorn:Asia:EasternAsia:Other' ,'ForeignBorn:Asia:SouthCentralAsia' ,
        'ForeignBorn:Asia:SouthCentralAsia:Afghanistan' ,'ForeignBorn:Asia:SouthCentralAsia:Bangladesh' ,'ForeignBorn:Asia:SouthCentralAsia:India' ,
        'ForeignBorn:Asia:SouthCentralAsia:Iran' ,'ForeignBorn:Asia:SouthCentralAsia:Kazakhstan' ,'ForeignBorn:Asia:SouthCentralAsia:Nepal' ,
        'ForeignBorn:Asia:SouthCentralAsia:Pakistan' ,'ForeignBorn:Asia:SouthCentralAsia:Sri Lanka' ,'ForeignBorn:Asia:SouthCentralAsia:Uzbekistan' ,
        'ForeignBorn:Asia:SouthCentralAsia:Other' ,'ForeignBorn:Asia:SouthEasternAsia' ,'ForeignBorn:Asia:SouthEasternAsia:Burma' ,
        'ForeignBorn:Asia:SouthEasternAsia:Cambodia' ,'ForeignBorn:Asia:SouthEasternAsia:Indonesia' ,'ForeignBorn:Asia:SouthEasternAsia:Laos' ,
        'ForeignBorn:Asia:SouthEasternAsia:Malaysia' ,'ForeignBorn:Asia:SouthEasternAsia:Philippines' ,'ForeignBorn:Asia:SouthEasternAsia:Singapore' ,
        'ForeignBorn:Asia:SouthEasternAsia:Thailand' ,'ForeignBorn:Asia:SouthEasternAsia:Vietnam' ,'ForeignBorn:Asia:SouthEasternAsia:Other' ,
        'ForeignBorn:Asia:WesternAsia' ,'ForeignBorn:Asia:WesternAsia:Armenia' ,'ForeignBorn:Asia:WesternAsia:Iraq' ,'ForeignBorn:Asia:WesternAsia:Israel' ,
        'ForeignBorn:Asia:WesternAsia:Jordan' ,'ForeignBorn:Asia:WesternAsia:Kuwait' ,'ForeignBorn:Asia:WesternAsia:Lebanon' ,
        'ForeignBorn:Asia:WesternAsia:Saudi Arabia' ,'ForeignBorn:Asia:WesternAsia:Syria' ,'ForeignBorn:Asia:WesternAsia:Turkey' ,
        'ForeignBorn:Asia:WesternAsia:Yemen' ,'ForeignBorn:Asia:WesternAsia:Other' ,'ForeignBorn:Africa:EasternAfrica' ,
        'ForeignBorn:Africa:EasternAfrica:Eritrea' ,'ForeignBorn:Africa:EasternAfrica:Ethiopia' ,'ForeignBorn:Africa:EasternAfrica:Kenya' ,
        'ForeignBorn:Africa:EasternAfrica:Somalia' ,'ForeignBorn:Africa:EasternAfrica:Uganda' ,'ForeignBorn:Africa:EasternAfrica:Zimbabwe' ,
        'ForeignBorn:Africa:EasternAfrica:Other' ,'ForeignBorn:Africa:MiddleAfrica' ,'ForeignBorn:Africa:MiddleAfrica:Cameroon' ,
        'ForeignBorn:Africa:MiddleAfrica:Congo' ,'ForeignBorn:Africa:MiddleAfrica:Democratic Republic of Congo (Zaire)' ,'ForeignBorn:Africa:MiddleAfrica:Other' ,
        'ForeignBorn:Africa:NorthernAfrica' ,'ForeignBorn:Africa:NorthernAfrica:Egypt' ,'ForeignBorn:Africa:NorthernAfrica:Morocco' ,
        'ForeignBorn:Africa:NorthernAfrica:Sudan' ,'ForeignBorn:Africa:NorthernAfrica:Other' ,'ForeignBorn:Africa:WesternAfrica' ,
        'ForeignBorn:Africa:WesternAfrica:Cabo Verde' ,'ForeignBorn:Africa:WesternAfrica:Ghana' ,'ForeignBorn:Africa:WesternAfrica:Liberia' ,
        'ForeignBorn:Africa:WesternAfrica:Nigeria' ,'ForeignBorn:Africa:WesternAfrica:Senegal' ,'ForeignBorn:Africa:WesternAfrica:Sierra Leone' ,
        'ForeignBorn:Africa:WesternAfrica:Other' ,'ForeignBorn:Oceania:Australia and New Zealand Subregion' ,
        'ForeignBorn:Oceania:Australia and New Zealand Subregion:Australia' ,'ForeignBorn:Oceania:Australia and New Zealand Subregion:Other' ,
        'ForeignBorn:Oceania:Fiji' ,'ForeignBorn:Oceania:Micronesia' ,'ForeignBorn:Central & South America, Caribbean:Caribbean' ,
        'ForeignBorn:Central & South America, Caribbean:Caribbean:Bahamas' ,'ForeignBorn:Central & South America, Caribbean:Caribbean:Barbados' ,
        'ForeignBorn:Central & South America, Caribbean:Caribbean:Cuba' ,'ForeignBorn:Central & South America, Caribbean:Caribbean:Dominica' ,
        'ForeignBorn:Central & South America, Caribbean:Caribbean:Dominican Republic' ,'ForeignBorn:Central & South America, Caribbean:Caribbean:Grenada' ,
        'ForeignBorn:Central & South America, Caribbean:Caribbean:Haiti' ,'ForeignBorn:Central & South America, Caribbean:Caribbean:Jamaica' ,
        'ForeignBorn:Central & South America, Caribbean:Caribbean:St. Vincent and the Grenadines' ,
        'ForeignBorn:Central & South America, Caribbean:Caribbean:Trinidad and Tobago' ,'ForeignBorn:Central & South America, Caribbean:Caribbean:West Indies' ,
        'ForeignBorn:Central & South America, Caribbean:Caribbean:Other' ,'ForeignBorn:Central & South America, Caribbean:Central America' ,
        'ForeignBorn:Central & South America, Caribbean:Central America:Belize' ,'ForeignBorn:Central & South America, Caribbean:Central America:Costa Rica' ,
        'ForeignBorn:Central & South America, Caribbean:Central America:El Salvador' ,'ForeignBorn:Central & South America, Caribbean:Central America:Guatemala' ,
        'ForeignBorn:Central & South America, Caribbean:Central America:Honduras' ,'ForeignBorn:Central & South America, Caribbean:Central America:Mexico' ,
        'ForeignBorn:Central & South America, Caribbean:Central America:Nicaragua' ,'ForeignBorn:Central & South America, Caribbean:Central America:Panama' ,
        'ForeignBorn:Central & South America, Caribbean:Central America:Other' ,'ForeignBorn:Central & South America, Caribbean:South America' ,
        'ForeignBorn:Central & South America, Caribbean:South America:Argentina' ,'ForeignBorn:Central & South America, Caribbean:South America:Bolivia' ,
        'ForeignBorn:Central & South America, Caribbean:South America:Brazil' ,'ForeignBorn:Central & South America, Caribbean:South America:Chile' ,
        'ForeignBorn:Central & South America, Caribbean:South America:Columbia' ,'ForeignBorn:Central & South America, Caribbean:South America:Ecuador' ,
        'ForeignBorn:Central & South America, Caribbean:South America:Guyana' ,'ForeignBorn:Central & South America, Caribbean:South America:Peru' ,
        'ForeignBorn:Central & South America, Caribbean:South America:Uruguay' ,'ForeignBorn:Central & South America, Caribbean:South America:Venezuela' ,
        'ForeignBorn:Central & South America, Caribbean:South America:Other' ,'ForeignBorn:Canada & Other Northern American:Canada' ,
        'ForeignBorn:Canada & Other Northern American:Other']
        
cols2 = ['NAME', 'Foreign Born Population %']
data1 = data.loc[data['NAME'].isin(geos)]
data1 = data1[cols1]
totalforeignborn = data.loc[data['NAME'].isin(geos)]
totalforeignborn = totalforeignborn[cols2]

In [5]:
data1.head(2)

,NAME,Foreign Born Population,ForeignBorn:Europe,ForeignBorn:Asia,ForeignBorn:Africa,ForeignBorn:Oceania,ForeignBorn:Americas,"ForeignBorn:Central & South America, Caribbean",ForeignBorn:Canada & Other Northern American,ForeignBorn:Europe:NorthernEurope,...,"ForeignBorn:Central & South America, Caribbean:South America:Chile","ForeignBorn:Central & South America, Caribbean:South America:Columbia","ForeignBorn:Central & South America, Caribbean:South America:Ecuador","ForeignBorn:Central & South America, Caribbean:South America:Guyana","ForeignBorn:Central & South America, Caribbean:South America:Peru","ForeignBorn:Central & South America, Caribbean:South America:Uruguay","ForeignBorn:Central & South America, Caribbean:South America:Venezuela","ForeignBorn:Central & South America, Caribbean:South America:Other",ForeignBorn:Canada & Other Northern American:Canada,ForeignBorn:Canada & Other Northern American:Other
10,"Cheatham County, Tennessee",1287.0,165.0,292.0,30.0,3.0,797.0,713.0,84.0,72.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,84.0,0.0
18,"Davidson County, Tennessee",107179.0,6184.0,24743.0,20858.0,664.0,54730.0,52263.0,2467.0,1768.0,...,150.0,1436.0,195.0,98.0,483.0,14.0,1579.0,19.0,2467.0,0.0

In [6]:
totalforeignborn

                            NAME  Foreign Born Population %
10    Cheatham County, Tennessee                   3.076813
18    Davidson County, Tennessee                  14.981940
21     Dickson County, Tennessee                   2.043477
41     Houston County, Tennessee                   1.280977
42   Humphreys County, Tennessee                   1.753929
59       Maury County, Tennessee                   3.851899
62  Montgomery County, Tennessee                   6.838691
73   Robertson County, Tennessee                   5.586518
74  Rutherford County, Tennessee                  10.899053
80     Stewart County, Tennessee                   2.245669
82      Sumner County, Tennessee                   4.028881
84   Trousdale County, Tennessee                   2.249728
93  Williamson County, Tennessee                   8.495838
94      Wilson County, Tennessee                   6.579768

In [7]:
cols = data1.columns
data1 = data1.melt(id_vars = 'NAME', value_vars = cols, var_name = 'Population Group', value_name = 'Population').sort_values(by = 'NAME')
data1 = data1.sort_values(by = 'Population Group')

In [8]:
data1.head(18)

                            NAME         Population Group  Population
0     Cheatham County, Tennessee  Foreign Born Population      1287.0
2      Dickson County, Tennessee  Foreign Born Population      1144.0
4    Humphreys County, Tennessee  Foreign Born Population       337.0
5        Maury County, Tennessee  Foreign Born Population      4152.0
7    Robertson County, Tennessee  Foreign Born Population      4220.0
1     Davidson County, Tennessee  Foreign Born Population    107179.0
12  Williamson County, Tennessee  Foreign Born Population     22119.0
8   Rutherford County, Tennessee  Foreign Born Population     39307.0
10      Sumner County, Tennessee  Foreign Born Population      8236.0
13      Wilson County, Tennessee  Foreign Born Population     10449.0
6   Montgomery County, Tennessee  Foreign Born Population     16013.0
3      Houston County, Tennessee  Foreign Born Population       107.0
9      Stewart County, Tennessee  Foreign Born Population       315.0
11   Trousdale County, Tennessee  Foreign Born Population       269.0
46   Humphreys County, Tennessee       ForeignBorn:Africa         0.0
44     Dickson County, Tennessee       ForeignBorn:Africa         0.0
53   Trousdale County, Tennessee       ForeignBorn:Africa         0.0
51     Stewart County, Tennessee       ForeignBorn:Africa         0.0

In [9]:
counties = ['Cheatham County, Tennessee', 'Davidson County, Tennessee', 'Dickson County, Tennessee', 'Houston County, Tennessee', 'Humphreys County, Tennessee',
            'Maury County, Tennessee', 'Montgomery County, Tennessee', 'Robertson County, Tennessee', 'Rutherford County, Tennessee', 'Stewart County, Tennessee', 
            'Sumner County, Tennessee', 'Trousdale County, Tennessee', 'Williamson County, Tennessee', 'Wilson County, Tennessee']

for county in counties:
    df = data1.loc[data1['NAME'] == county].copy().reset_index(drop=True)

    #get fb pop for x county
    foreign_born = df.loc[df['Population Group'] == 'Foreign Born Population', 'Population'].iloc[0]

    #calc percentages
    df['Percent of Foreign Born Population'] = (df['Population'] / foreign_born) * 100

    #sort, export
    df = df.sort_values(by='Percent of Foreign Born Population', ascending=False)

    df.to_csv(r'G:\3-GitHub\AAAD-Senior-Center-Profiles\1-data\3-processed\{}_2024.csv'.format(county), index=False)

In [10]:
df.head()

,NAME,Population Group,Population,Percent of Foreign Born Population
0,"Wilson County, Tennessee",Foreign Born Population,10449.0,100.000000
28,"Wilson County, Tennessee",ForeignBorn:Americas,5109.0,48.894631
75,"Wilson County, Tennessee","ForeignBorn:Central & South America, Caribbean",4721.0,45.181357
89,"Wilson County, Tennessee","ForeignBorn:Central & South America, Caribbean...",3588.0,34.338214
29,"Wilson County, Tennessee",ForeignBorn:Asia,2679.0,25.638817